name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}      


    - name: Docker Build
      run: docker build . -t index.docker.io/maxiplux/fastapidevops
    - name: Docker Push
      run: docker push index.docker.io/maxiplux/fastapidevops
