name: Docker Image CI

on:
  push:
    branches: [  "dev-auth" ]
  pull_request:
    branches: [  "dev-auth"  ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}

      - name: Docker Builder Buidx
        run: docker buildx create --use --platform=linux/arm64,linux/amd64 --name multi-platform-builder

      - name: Docker Build
        run:  docker buildx build --platform linux/amd64,linux/arm64 . maxiplux/fastapidevops-auth:latest
      - name: Docker Push
        run: docker push index.docker.io/maxiplux/fastapidevops-auth


