name: Docker Image CI

on:
  push:
    branches: [  "dev-auth" ]
  pull_request:
    branches: [  "dev-auth"  ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}


      - name: Docker Build
        run: docker build . -t index.docker.io/maxiplux/fastapidevops-auth
      - name: Docker Push
        run: docker push index.docker.io/maxiplux/fastapidevops-auth
